version: '3.7'
services:
  docker-fastapi:
    depends_on:
      - postgres
    container_name: docker-fastapi
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file:
      - ./local_dev.env
    restart: always
    networks:
      - postgres
    ports:
      - "81:81"
  nginx:
    depends_on:
      - docker-fastapi
    container_name: proxy-app
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    env_file:
      - ./local_dev.env
    ports:
      - "80:80"
    restart: always
    networks:
      - postgres
  postgres:
    container_name: postgres_db
    image: postgres
    restart: always
    env_file:
      - ./local_dev.env
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes: 
      - db:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local

networks:
  postgres:
    driver: bridge



