"""

Revision ID: 084d702ac87d
Revises: a6157303a9b1
Create Date: 2022-11-21 22:43:31.712522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084d702ac87d'
down_revision = 'a6157303a9b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('jwt_token', sa.String(length=500), nullable=True))
    op.drop_column('users', 'created_recipes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_recipes', sa.INTEGER(), nullable=True))
    op.drop_column('users', 'jwt_token')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
