"""

Revision ID: 14e315ad2a32
Revises: 
Create Date: 2022-11-24 12:45:31.559563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e315ad2a32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(length=100), nullable=False),
    sa.Column('family_name', sa.String(length=100), nullable=False),
    sa.Column('picture', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('area', sa.String(length=30), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('ingredients_measurements', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['area'], ['areas.name'], name='fk_recipes_areas_name_area'),
    sa.ForeignKeyConstraint(['category'], ['categories.name'], name='fk_recipes_categories_name_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredients.id'], name='fk_users_ingredients_ingredients_ingredient_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_users_ingredients_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.Integer(), nullable=True),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredients.id'], name='fk_recipes_ingredients_ingredients_ingredient_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name='fk_recipes_ingredients_recipes_recipe_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_created_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name='fk_users_created_recipes_recipes_id_recipe'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_users_created_recipes_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('users_saved_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name='fk_users_saved_recipes_recipes_id_recipe'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_users_saved_recipes_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_saved_recipes')
    op.drop_table('users_created_recipes')
    op.drop_table('recipes_ingredients')
    op.drop_table('users_ingredients')
    op.drop_table('recipes')
    op.drop_table('users')
    op.drop_table('ingredients')
    op.drop_table('categories')
    op.drop_table('areas')
    # ### end Alembic commands ###
