"""

Revision ID: 4ab8cffd760c
Revises: 084d702ac87d
Create Date: 2022-11-22 09:13:48.131227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab8cffd760c'
down_revision = '084d702ac87d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.Integer(), nullable=True),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredients.id'], name='fk_recipes_ingredients_ingredients_ingredient_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name='fk_recipes_ingredients_recipes_recipe_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipes_ingredients_measurements')
    op.drop_table('measurements')
    op.alter_column('users', 'given_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'family_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'picture',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'picture',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'family_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'given_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table('measurements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('measurement', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement')
    )
    op.create_table('recipes_ingredients_measurements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ingredient', sa.INTEGER(), nullable=True),
    sa.Column('measurement', sa.INTEGER(), nullable=True),
    sa.Column('recipe', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredients.id'], name='fk_recipes_ingredients_measurements_ingredients_id_ingredient'),
    sa.ForeignKeyConstraint(['measurement'], ['measurements.id'], name='fk_recipes_ingredients_measurements_measurements_id_measurement'),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name='fk_recipes_ingredients_measurements_recipes_id_recipe'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient', 'measurement', 'recipe', name='uc_recipes_ingredients_measurements_ingredient_measurement_recipe')
    )
    op.drop_table('recipes_ingredients')
    # ### end Alembic commands ###
