"""

Revision ID: 5e32e57cddbb
Revises: 14e315ad2a32
Create Date: 2022-11-24 12:53:02.439107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e32e57cddbb'
down_revision = '14e315ad2a32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'areas', ['name'])
    op.create_unique_constraint(None, 'categories', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'areas', type_='unique')
    # ### end Alembic commands ###
