"""

Revision ID: 5e75053ee3df
Revises: 
Create Date: 2022-10-31 10:43:02.758724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e75053ee3df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measurement', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measurement')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.Column('area', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('ingredients_measurements', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['area'], ['areas.id'], name='fk_recipes_areas_id_area'),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], name='fk_recipes_categories_id_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes_ingredients_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient', sa.Integer(), nullable=True),
    sa.Column('measurement', sa.Integer(), nullable=True),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient'], ['ingredients.id'], name='fk_recipes_ingredients_measurements_ingredients_id_ingredient'),
    sa.ForeignKeyConstraint(['measurement'], ['measurements.id'], name='fk_recipes_ingredients_measurements_measurements_id_measurement'),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name='fk_recipes_ingredients_measurements_recipes_id_recipe'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient', 'measurement', 'recipe', name='uc_recipes_ingredients_measurements_ingredient_measurement_recipe')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes_ingredients_measurements')
    op.drop_table('recipes')
    op.drop_table('users')
    op.drop_table('measurements')
    op.drop_table('ingredients')
    op.drop_table('categories')
    op.drop_table('areas')
    # ### end Alembic commands ###
