"""

Revision ID: 7bf8a2b239d6
Revises: 900f67dd4002
Create Date: 2022-11-27 14:29:19.266592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf8a2b239d6'
down_revision = '900f67dd4002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_created_recipes_user_key', 'users_created_recipes', type_='unique')
    op.drop_constraint('users_saved_recipes_user_key', 'users_saved_recipes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_saved_recipes_user_key', 'users_saved_recipes', ['user'])
    op.create_unique_constraint('users_created_recipes_user_key', 'users_created_recipes', ['user'])
    # ### end Alembic commands ###
