"""upgrade message

Revision ID: 8250b2eefdb9
Revises: 5e32e57cddbb
Create Date: 2022-11-25 03:06:17.709965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8250b2eefdb9'
down_revision = '5e32e57cddbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
