"""

Revision ID: 8af18b5651ba
Revises: e5d54acd0496
Create Date: 2022-12-01 13:30:23.294254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af18b5651ba'
down_revision = 'e5d54acd0496'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_ingredients_ingredients_ingredient_id', 'users_ingredients', type_='foreignkey')
    op.drop_constraint('fk_users_ingredients_users_user_id', 'users_ingredients', type_='foreignkey')
    op.create_foreign_key('fk_users_ingredients_ingredients_id_ingredient', 'users_ingredients', 'ingredients', ['ingredient'], ['id'])
    op.create_foreign_key('fk_users_ingredients_users_id_user', 'users_ingredients', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_ingredients_users_id_user', 'users_ingredients', type_='foreignkey')
    op.drop_constraint('fk_users_ingredients_ingredients_id_ingredient', 'users_ingredients', type_='foreignkey')
    op.create_foreign_key('fk_users_ingredients_users_user_id', 'users_ingredients', 'users', ['user'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('fk_users_ingredients_ingredients_ingredient_id', 'users_ingredients', 'ingredients', ['ingredient'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
