"""

Revision ID: 94a9d57e0283
Revises: 8af18b5651ba
Create Date: 2022-12-01 14:00:34.749291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a9d57e0283'
down_revision = '8af18b5651ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
