"""

Revision ID: a6157303a9b1
Revises: 8723b6f2217a
Create Date: 2022-11-18 17:48:13.645644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6157303a9b1'
down_revision = '8723b6f2217a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name='fk_users_recipes_recipes_recipe_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_users_recipes_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('recipes_users')
    op.drop_column('recipes', 'saved_by')
    op.drop_column('recipes', 'created_by')
    with op.batch_alter_table(
        "users",
        reflect_args=[sa.Column('flag', sa.Boolean(create_constraint=True))],
    ) as batch_op:
        batch_op.add_column(sa.Column('created_recipes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_recipes_id_created_recipes', 'users', type_='foreignkey')
    op.drop_column('users', 'created_recipes')
    op.add_column('recipes', sa.Column('created_by', sa.INTEGER(), nullable=True))
    op.add_column('recipes', sa.Column('saved_by', sa.INTEGER(), nullable=True))
    op.create_table('recipes_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=True),
    sa.Column('recipe', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['recipe'], ['recipes.id'], name='fk_recipes_users_recipes_recipe_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_recipes_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users_recipes')
    # ### end Alembic commands ###
