"""update message goes here

Revision ID: e99cae9cc0c6
Revises: bda20746834b
Create Date: 2022-11-02 01:35:36.559895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e99cae9cc0c6'
down_revision = 'bda20746834b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('given_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('family_name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('picture', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=20), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('users', 'email')
    op.drop_column('users', 'picture')
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'given_name')
    # ### end Alembic commands ###
